/**
 * Multilingual Prohibited / Abusive Terms Dataset
 *
 * Source Attribution:
 * Derived in part from the List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words (LDNOOBW)
 * repository: https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
 * Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0).
 *
 * Includes terms across English (en), Hindi (hi), Spanish (es), French (fr), German (de),
 * and high-severity hate speech / slurs / sexually explicit terminology.
 */

export const PROHIBITED_WORDS: ReadonlySet<string> = new Set([
  // --- High-severity profanities & slurs (English) ---
  "fuck",
  "fucker",
  "fucking",
  "fuckhead",
  "fack",
  "fuk",
  "fukk",
  "fck",
  "fckr",
  "fcker",
  "motherfucker",
  "motherfucking",
  "shit",
  "shitting",
  "shithead",
  "shyt",
  "bullshit",
  "bitch",
  "bitches",
  "bitching",
  "btch",
  "b1tch",
  "asshole",
  "azzhole",
  "bastard",
  "cunt",
  "cunts",
  "dick",
  "dickhead",
  "dildo",
  "whore",
  "slut",
  "nigger",
  "nigga",
  "faggot",
  "fag",
  "dyke",
  "kike",
  "chink",
  "gook",
  "spic",
  "twat",
  "pussy",
  "cock",
  "cocksucker",
  "blowjob",
  "handjob",
  "cum",
  "cumshot",
  "ejaculation",
  "orgasm",
  "masturbate",
  "masturbation",
  "porn",
  "porno",
  "pornography",
  "pedophile",
  "paedophile",
  "pedophilia",
  "rape",
  "rapist",
  "raping",
  "molest",
  "molester",
  "bestiality",
  "necrophilia",
  "nazi",
  "hitler",
  "swastika",
  "jihadist",
  "terrorist",
  "suicide",
  "killall",
  "genocide",

  // --- Common Obscenities (English) ---
  "anal",
  "anus",
  "ballsack",
  "blow job",
  "boner",
  "boob",
  "boobs",
  "booty",
  "clit",
  "clitoris",
  "coot",
  "coon",
  "condom",
  "deepthroat",
  "dildo",
  "dominatrix",
  "erotic",
  "escort",
  "felch",
  "fellate",
  "fellatio",
  "gangbang",
  "hentai",
  "hooker",
  "horny",
  "incest",
  "jerkoff",
  "labia",
  "milf",
  "naked",
  "nude",
  "nudity",
  "orgies",
  "orgy",
  "penis",
  "playboy",
  "prick",
  "prostitute",
  "rectum",
  "rimjob",
  "sadism",
  "scrotum",
  "semen",
  "sex",
  "sexy",
  "shemale",
  "skank",
  "smut",
  "sodomize",
  "sodomy",
  "sperm",
  "testicle",
  "tits",
  "titties",
  "tosser",
  "vagina",
  "viagra",
  "vulva",
  "wank",
  "wanker",
  "xxx",

  // --- Hindi / South Asian (hi) Profanities & Slurs ---
  "bhosdi",
  "bhosdike",
  "bhosadike",
  "bhosad",
  "madarchod",
  "behenchod",
  "bhenchod",
  "betichod",
  "chutiya",
  "chutiye",
  "choot",
  "gand",
  "gaand",
  "gandu",
  "gaandu",
  "lund",
  "lauda",
  "lavda",
  "lodha",
  "randi",
  "raand",
  "harami",
  "harramkhor",
  "kamina",
  "kamine",
  "saala",
  "kutte",
  "kutta",
  "hijra",
  "chakka",
  "randibaaz",
  "muth",
  "mutthal",
  "jhaat",
  "jhat",

  // --- Spanish (es) ---
  "puta",
  "puto",
  "mierda",
  "pendejo",
  "pendeja",
  "cabron",
  "cabrona",
  "chingar",
  "chingada",
  "verga",
  "coño",
  "maricon",
  "culero",
  "jodido",
  "gilipollas",
  "hijo de puta",

  // --- French (fr) ---
  "merde",
  "connard",
  "connasse",
  "putain",
  "salope",
  "encule",
  "enculer",
  "bite",
  "chienne",
  "batard",

  // --- German (de) ---
  "arschloch",
  "scheisse",
  "scheiße",
  "hurensohn",
  "schlampe",
  "wichser",
  "fotze",
  "bastard",
]);

/**
 * High-severity substrings that should not appear anywhere in a username,
 * unless explicitly allowed by the allowlist exception mechanism.
 */
export const SEVERE_SUBSTRINGS: readonly string[] = [
  "nigger",
  "nigga",
  "faggot",
  "chink",
  "kike",
  "cunt",
  "bhosdike",
  "madarchod",
  "behenchod",
  "hitler",
  "pedophile",
  "paedophile",
  "rapist",
];
